# Generated by Django 5.2.6 on 2026-03-30 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_user_adresses'),
        ('profileApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.user_adresses'),
        ),
    ]
