# Generated by Django 5.2.6 on 2026-03-30 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profileApp', '0003_profile_telegram_alter_profile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
