# Generated by Django 5.2.6 on 2026-03-18 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_adresses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(choices=[('home', 'Домашний'), ('work', 'Рабочий'), ('other', 'Другой')], default='home', max_length=20, verbose_name='Тип адреса')),
                ('is_default', models.BooleanField(default=False, verbose_name='Основной адрес')),
                ('city', models.CharField(max_length=100, verbose_name='Город')),
                ('street', models.CharField(max_length=200, verbose_name='Улица')),
                ('house', models.CharField(max_length=20, verbose_name='Дом')),
                ('apartment', models.CharField(blank=True, max_length=20, verbose_name='Квартира/офис')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='authorization.users', verbose_name='Пользователь')),
            ],
        ),
    ]
