# Generated by Django 5.2.6 on 2026-03-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0002_user_adresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_adresses',
            name='comment',
            field=models.CharField(blank=True, max_length=150, verbose_name='Комментарий'),
        ),
    ]
