# Generated by Django 5.2.6 on 2026-03-31 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0003_user_adresses_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_adresses',
            name='doorphone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Домофон'),
        ),
        migrations.AddField(
            model_name='user_adresses',
            name='entrance',
            field=models.CharField(blank=True, max_length=20, verbose_name='Подъезд'),
        ),
        migrations.AddField(
            model_name='user_adresses',
            name='floor',
            field=models.CharField(blank=True, max_length=20, verbose_name='Этаж'),
        ),
    ]
