# Generated by Django 5.2.6 on 2026-03-31 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorization', '0004_user_adresses_doorphone_user_adresses_entrance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_adresses',
            old_name='doorphone',
            new_name='intercom',
        ),
    ]
