# Generated by Django 5.2.6 on 2026-02-23 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authorization', '0001_initial'),
        ('menu', '0004_dishes_image_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dishes_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.dishes')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authorization.users')),
            ],
        ),
    ]
