# Generated by Django 5.2.6 on 2026-02-24 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_sum',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
