# Generated by Django 5.2.6 on 2026-02-24 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0002_cart_total_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Общая цена'),
        ),
    ]
