# Generated by Django 5.2.6 on 2026-03-16 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basket', '0004_promocode_promocodeusage'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='applied_promo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='basket.promocode'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_sum',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Цена товара'),
        ),
    ]
