# Generated by Django 5.2.6 on 2026-02-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_dishes_category_dishes_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dishes',
            name='image_path',
            field=models.CharField(default='error', max_length=255),
        ),
    ]
